version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - app

  keycloak-countries:
    image: jboss/keycloak
    container_name: keycloak-countries
    environment:
      KEYCLOAK_USER: test
      KEYCLOAK_PASSWORD: test
    volumes:
      - ../keycloak/keycloak-forgot-password-plugin-1.0-SNAPSHOT.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-forgot-password-plugin.jar
    ports:
      - "8491:8080"
    networks:
      - app
    restart: unless-stopped

networks:
  app:
    driver: bridge