server:
  port: 8090

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/countries
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8491/auth/realms/countries-and-cities
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: countries-auth
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: http://localhost:8491/login/oauth2/code/keycloak
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8491/auth/realms/countries-and-cities

springdoc:
  api-docs:
    enabled: true


